name: family_budget
description: university work.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.3.1
  dio_cookie_manager: ^3.1.0
  mask_text_input_formatter: ^2.4.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  fl_chart: ^0.64.0
  intl: ^0.18.1
  image_picker: ^1.0.1
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.1.1
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  google_fonts: ^5.0.0
  shared_preferences: ^2.0.18
  injectable: ^2.3.0
  get_it: ^7.6.4
  provider: ^6.0.5
  auto_route: ^7.8.3
  flutter_gen_runner: ^5.3.1
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.0.2
  widget_size: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  injectable_generator: ^2.4.0
  auto_route_generator: ^7.3.1
  freezed: ^2.4.1

flutter:

  uses-material-design: true

  assets:
    - env/
    - assets/images/
    - assets/icons/

