name: family_budget
description: university work.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  hugeicons: ^0.0.7
  dio: ^5.3.1
  mask_text_input_formatter: ^2.9.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.64.0
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^8.1.3
  flutter_colorpicker: ^1.1.0
  fluttertoast: ^8.1.1
#  firebase_core: ^2.15.0
#  firebase_messaging: ^14.6.5
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.5
  injectable: ^2.5.0
  get_it: ^7.6.4
  provider: ^6.0.5
  timezone: ^0.9.0
  auto_route: ^9.3.0
  flutter_gen_runner: ^5.8.0
  flutter_native_splash: ^2.3.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.7
  flutter_slidable: ^3.1.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.0.2
  gif: ^2.3.0

#  flutter_local_notifications: ^17.2.1
  flutter_background_service: ^5.0.9
  flutter_background_service_android: ^6.0.0
  flutter_background_service_ios: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3


  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.9.0
  injectable_generator: ^2.6.2
  auto_route_generator: ^9.0.0
  freezed: ^2.5.7
  launcher_name: ^1.0.2

launcher_name:
  default: "Budget Control"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launch_icon.jpg"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - env/
    - assets/icons/
    - assets/icons/categories/
    - assets/gif/
    - assets/images/

